BREAKING CHANGE: add message level support to policy
gravitee-io/gravitee-policy-assign-attributes pull request #24
Opened 2023-06-08 20:09 UTC by remibaptistegio

**Issue**

https://gravitee.atlassian.net/browse/APIM-61

**Description**

Add message level support to policy.

2023-06-09 06:48 UTC, jhaeyaert requested changes
I've put some suggestions. 
Also, I don't get the BREAKING_CHANGE knowing that you are inheriting the AssignAttributesV3 policy. Is there something I missed?

2023-06-09 06:48 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +            return Flowable.fromIterable(assignVariablePolicyConfiguration.getAttributes()).filter(this::checkAttributeNameAndValue);
Is it possible to move this in a variable for further reuse in order to avoid recreating it for each request / message?

2023-06-09 06:48 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +                    .doOnError(t -> log.error("An error occurs while decoding context attribute", t))
We should avoid constantly logging the complete stack trace. It could log too much. We could add information such as _enable debug level for io.gravitee.policy.assignattributes.AssignAttributesPolicy to log the full stacktrace_ and log the stacktrace accordingly. wdyt?

2023-06-09 06:48 UTC, jhaeyaert commented on src/test/java/io/gravitee/policy/assignattributes/AssignAttributesPolicyTest.java
> +        public void shouldNotAssignAttributeWhenConfigEmpty() {
I remember the team opted for a naming convention such as `should_not_assign_attribute_when_config_empty`.

2023-06-09 06:48 UTC, jhaeyaert commented on src/test/java/io/gravitee/policy/assignattributes/AssignAttributesPolicyTest.java
> +            var request = new FakeRequest();
(For my own knowledge, not important) Why create a FakeRequest vs using a regular mock?

2023-06-09 06:48 UTC, jhaeyaert commented on src/test/java/io/gravitee/policy/assignattributes/AssignAttributesPolicyV3EngineIntegrationTest.java
> +            .await()
Just to be sure you not missed it, you should add a timeout to avoid blocking indefinitely in case of error during unit tests (at least 10s or 20s)

2023-06-12 08:57 UTC, remibaptistegio commented on src/test/java/io/gravitee/policy/assignattributes/AssignAttributesPolicyTest.java
> +            var request = new FakeRequest();
I've managed to use only mock ;)

2023-06-12 08:58 UTC, remibaptistegio commented on src/test/java/io/gravitee/policy/assignattributes/AssignAttributesPolicyV3EngineIntegrationTest.java
> +            .await()
fixed

2023-06-12 08:59 UTC, remibaptistegio commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +                    .doOnError(t -> log.error("An error occurs while decoding context attribute", t))
I've removed the log and added an interrupt if an error occurred. Is it ok for you ?

2023-06-12 09:10 UTC, jhaeyaert requested changes

2023-06-12 09:10 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +    private final Flowable<Attribute> attributeFlowable = Flowable.defer(() ->
Does the `defer(...)` is really needed here? Also, you should probably add a `.cache()` so the attribute filtering is made only once. wdyt?

2023-06-12 09:10 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +                executionContext.interruptWith(
That sounds great to me.
As discussed, I prefer having an explicit error than just a log (inaccessible from the api publisher most of the time). So it means that there is a real BREAKING CHANGE now 🙂
@guillaumelamirand @brasseld can we have your feeling about breaking the execution when there is trouble with assigning attributes (ex: EL expression fails) instead of just logging? Are you comfortable with this BC?

2023-06-12 12:27 UTC, remibaptistegio commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +    private final Flowable<Attribute> attributeFlowable = Flowable.defer(() ->
Fixed, I had an issue in my unit test that I fixed and now the defer is indeed not needed.

2023-06-15 07:02 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +                executionContext.interruptWith(
If I remember, for conditions we distinguished two types of errors ?
- the EL is invalid because of bad syntax, so it should break
- the EL try to access a null value (the case of an absent header for stuff like `request.headers[X-Toto][0] == 'totovalue'`), in this case it's another exception, and it is just skipped to not break.

Maybe we could apply the same kind of logic here:
- in case of invalid syntax, we break
- in case of evaluation problem, the attribute is just not set 

wdyt ?

2023-06-15 15:13 UTC, remibaptistegio commented on src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java
> +                executionContext.interruptWith(
I looked at the gravitee-expression-language repo and I did found two exceptions like you said, but the one for the null value (ELNullEvaluationException) is not used. We only throw the other one ExpressionEvaluationException I think :/

2023-06-16 08:53 UTC, jhaeyaert approved these changes

2023-06-20 12:18 UTC, merged

2023-06-20 12:24 UTC, graviteeio commented
:tada: This PR is included in version 1.6.0-alpha.1 :tada:

The release is available on:
- `1.6.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-assign-attributes/releases/tag/1.6.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-18 08:45 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `2.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-assign-attributes/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: